"""
This is a setup.py script generated by py2applet
 
Usage:
    python setup.py py2app
    
    
"""

#import getpass
from setuptools import setup
 
APP = ['Scout.py']
 
OPTIONS = {'argv_emulation': True, 'iconfile':'scout_logo.icns', 'includes':['pytube3', 'tkinter', 'wheel', 'ruamel'],
           'plist': {
               'PyRuntimeLocations': [
                '/usr/local/bin/python3'
               ]
           }}
 
setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# python3 setup.py py2app -A
# getpass.getuser()
