"""
This is a setup.py script generated by py2applet
 
Usage:
    python setup.py py2app
    
    
"""
 
from setuptools import setup
 
APP = ['Scout.py']
 
OPTIONS = {'argv_emulation': True, 'iconfile':'scout_logo.icns',
           'plist': {
               'PyRuntimeLocations': [
                '/Users/leif/opt/anaconda3/lib/libpython3.8.dylib'
               ]
           }}
 
setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# python3 setup.py py2app -A
